<Project Sdk="Microsoft.NET.Sdk.Worker">

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Bogus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TreeEditor.Data\TreeEditor.Data.csproj" />
    <ProjectReference Include="..\TreeEditor.Domain\TreeEditor.Domain.csproj" />
    <ProjectReference Include="..\TreeEditor.ServiceDefaults\TreeEditor.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
